Ticket8332 add ioc litron
ISISComputingGroup/EPICS-LITRON pull request #1
Opened 2024-12-04 15:37 UTC by esmith1729

Litron Laser control IOC, using LVRemote substitutions, similar to the [SXD Tensile Stress Rig](https://github.com/ISISComputingGroup/IBEX/issues/8264) 

- https://github.com/ISISComputingGroup/IBEX/issues/8332

2025-01-03 10:44 UTC, jackbdoughty requested changes

2025-01-03 10:44 UTC, jackbdoughty commented on system_tests/tests/litron.py
> +    def test_that_fails(self):
I think we could do with atleast some simple recsim tests here or to get rid of the unused emulator bits

2025-01-09 15:31 UTC, iangillingham-stfc commented
Started to review but didn't finish before my non-working days - so will return to 'review'.

2025-01-12 23:08 UTC, FreddieAkeroyd commented
Is it possible to write an emulalor of this? It is just sending `LVGET` and  `LVPUT` text commands from stream device that lewis should be able to emulate. Ideally we'd like a lvremote base class to inherit the emulator from, but that is beyond this ticket and may not be worth doing as i'm not sure how many lvremote iocs we'll develop in the end

2025-01-13 08:54 UTC, esmith1729 commented
It doesn't seem worth it to write an emulator for this, I think similarly as to why there was no emulator written for the DDS Stress Rig, which I was following as an example when writing this.

2025-01-14 19:41 UTC, FreddieAkeroyd approved these changes

2025-01-14 19:41 UTC, merged